name: prometheus_client_shelf
description: Dart implementation of the Prometheus client library providing a shelf integration.
version: 0.4.0+3
homepage: https://github.com/Fox32/prometheus_client

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  prometheus_client: ^0.4.0+1
  shelf: ^0.7.5
  collection: ^1.14.11

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  shelf_router: ^0.7.1
