name: prometheus_client_shelf
description: Dart implementation of the Prometheus client library providing a shelf integration.
version: 0.6.0
homepage: https://github.com/tentaclelabs/prometheus_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  prometheus_client: ^0.6.0
  shelf: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
  # Dependency is required for the example
  shelf_router: ^1.0.0

dependency_overrides:
  prometheus_client:
    path: ../prometheus_client
