name: (prometheus_client_shelf) Dart CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Install dependencies
      working-directory: ./prometheus_client_shelf
      run: pub get
    - name: Run tests
      working-directory: ./prometheus_client_shelf
      run: pub run test
    - name: (prometheus_client_shelf) Dart/Flutter Package Analyzer
      uses: axel-op/dart_package_analyzer@v2
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        relativePath: prometheus_client_shelf/
